### ISSUE TITLE
Disable merging of a PR

### ISSUE THREAD

**Issue by bradyclifford** [im-open/create-pr-and-merge-action#7]
Would it be possible to have a toggle that doesn't merge the PR.  Just creates it, allowing a manual merge.

**Comment by danielle-casella-adams** [comment]
@bradyclifford I hesitate to have a toggle here just because the action is a "create pr and merge" action.  Is there another action you're using at this point that just does the pr creation?

**Comment by bradyclifford** [comment]
Ya you can close this.  We ended up bringing in a new action.
https://github.com/im-open/create-pull-request
